In [27]:
import os
import numpy as np
import scipy.io.wavfile as wf
import matplotlib.pyplot as plt
import librosa
import pandas as pd

In [28]:
audio_dataset_path_a = 'C:/Users/heera/OneDrive - Heerak/Desktop/Dissertation/traindata/training-a'

In [29]:
alpha = 'C:/Users/heera/Desktop/Dissertation/traindata/a0001tp.wav'

In [30]:
metadata_a=pd.read_csv('C:/Users/heera/OneDrive - Heerak/Desktop/Dissertation/traindata/training-a/REFERENCE.csv',header= None)

In [31]:
metadata_a.head()

0      1  2
0  a0001.wav  a0001  1
1  a0002.wav  a0002  1
2  a0003.wav  a0003  1
3  a0004.wav  a0004  1
4  a0005.wav  a0005  1

In [32]:
metadata_a = metadata_a.rename(columns={0: "File_name",1:"names", 2: "Class"})

In [33]:
metadata_a['Class'] = metadata_a['Class'].map({1: 1, -1: 0})

In [34]:
metadata_a.head()

File_name  names  Class
0  a0001.wav  a0001      1
1  a0002.wav  a0002      1
2  a0003.wav  a0003      1
3  a0004.wav  a0004      1
4  a0005.wav  a0005      1

In [35]:
metadata_a['Class'].value_counts()

1    292
0    117
Name: Class, dtype: int64

In [40]:
def extract_feature(file_name):
    print("Extracting "+file_name+" ...")
    X, sample_rate = librosa.load(file_name)
    stft = np.abs(librosa.stft(X))
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
    mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),sr=sample_rate).T,axis=0)
    return np.hstack((mfccs,chroma,mel,contrast,tonnetz))


In [41]:
def extract_feature1(file_name):
    X, sample_rate = librosa.load(file_name)
    stft = np.abs(librosa.stft(X))
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
    mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X), sr=sample_rate).T,axis=0)
    return mfccs,chroma,mel,contrast,tonnetz

In [42]:
def features_extractor(file_name):
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    
    return mfccs_scaled_features

In [43]:
b1 = extract_feature(alpha)

Extracting C:/Users/heera/Desktop/Dissertation/traindata/a0001tp.wav ...


In [44]:
b1.shape

(193,)

In [45]:
b2 = extract_feature1(alpha)

In [46]:
b2

(array([-5.7027502e+02,  1.2356920e+02,  8.0899551e+01,  3.2086147e+01,
        -2.4344664e+00, -1.2008073e+01, -9.5548533e-02,  1.9669334e+01,
         3.2619598e+01,  3.1467825e+01,  1.9105337e+01,  4.8727589e+00,
        -2.4746568e+00, -2.3282865e-01,  7.5808406e+00,  1.4050789e+01,
         1.4485862e+01,  9.2299423e+00,  2.5997272e+00, -7.6624560e-01,
         7.4448252e-01,  4.9765210e+00,  8.0545092e+00,  7.4127483e+00,
         3.5214355e+00, -7.7413642e-01, -2.5497599e+00, -8.9655238e-01,
         2.6644368e+00,  5.5413251e+00,  6.0078158e+00,  4.2518806e+00,
         1.9048506e+00,  6.1427140e-01,  8.5336256e-01,  1.8187358e+00,
         2.3253608e+00,  1.8504550e+00,  8.7003553e-01,  3.0133569e-01],
       dtype=float32),
 array([0.48102635, 0.5095136 , 0.551419  , 0.65250164, 0.71487856,
        0.73738664, 0.7155817 , 0.7389817 , 0.9713474 , 0.7996951 ,
        0.6368212 , 0.4910174 ], dtype=float32),
 array([7.79254818e+00, 3.53110075e+00, 9.59840834e-01, 4.69720036e-01,

In [47]:
b3 = features_extractor(alpha)

In [48]:
b3.shape

(40,)

In [49]:
def energy(signal_in):
    return [x**2 for x in signal_in]

def shannon_entrophy(signal_in):
    return [(-abs(x) * (logarithm(x))) for x in signal_in]
    
def shannon_energy(signal_in):
    return [((-(x**2)) * (logarithm(x**2))) for x in signal_in]    
    
def logarithm(x):
    if x == 0:
        return 0
    else:
        return np.log10(x)
        
def moving_average(signal_in, n = 100) :
    mov_av = np.zeros(len(signal_in))
    mov_av[0:n - 1] = signal_in[0:n - 1]
    for t in range(n - 1, len(mov_av)):
        mov_av[t] = np.average(signal_in[t - n + 1 : t])
    return mov_av

In [ ]:
def features_extractor(file_name):
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
    return